version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: devhub-mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: devhub
    volumes:
      - mongodb_dev_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - devhub-dev-network

  # Backend API (Development)
  server:
    build:
      context: .
      dockerfile: Dockerfile.server.dev
    container_name: devhub-server-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/devhub?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      JWT_EXPIRE: 7d
      CLIENT_URL: http://localhost:5173
    depends_on:
      - mongodb
    networks:
      - devhub-dev-network
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev

  # Frontend (Development)
  client:
    build:
      context: .
      dockerfile: Dockerfile.client.dev
    container_name: devhub-client-dev
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - server
    networks:
      - devhub-dev-network
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm run dev

  # MongoDB Admin Interface
  mongo-express:
    image: mongo-express:1.0.0
    container_name: devhub-mongo-express-dev
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    depends_on:
      - mongodb
    networks:
      - devhub-dev-network

volumes:
  mongodb_dev_data:

networks:
  devhub-dev-network:
    driver: bridge
